// aprendiendo_angular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from 'src/app/models/article';
import { Global } from 'src/app/services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {
  @Input() articles!: Article[];
  public url: string;

  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {
  }

}

<div class="loading" *ngIf="!articles">
    Cargando ...
</div>
<div class="loading" *ngIf="articles && articles.length == 0">
    No hay artículos para mostrar, inténtalo más tarde
</div>
<div id="articles" *ngIf="articles">
    <article class="article-item" *ngFor="let article of articles">
        <div class="image-wrap" *ngIf="article.image">
            <img src="{{url+ 'get-image/' + article.image}}" alt="{{article.title}}" />
        </div>
        <div class="image-wrap" *ngIf="!article.image">
            <img src="../../../assets/images/default.jpg" alt="{{article.title}}" />
        </div>

        <h2>{{article.title}}</h2>
        <span class="date">
            {{article.date | amLocale: 'es' | amTimeAgo }}
        </span>
        <a  [routerLink]="['/blog/articulo', article._id]">Leer más</a>

        <div class="clearfix"></div>
    </article>
</div>

// aprendiendo_vue/src/components/Articles.vue
<template>
  <section id="articles-component">
    <div id="articles-list" v-if="articles && articles.length >= 1">
      <article
        class="article-item"
        v-for="article in articles"
        :key="article._id"
      >
        <div class="image-wrap">
          <img
            :src="url + 'get-image/' + article.image"
            :alt="article.title"
            v-if="article.image"
          />
          <img
            src="../assets/images/default.jpg"
            :alt="article.title"
            v-if="!article.image"
          />
        </div>

        <h2>
          <router-link :to="{ name: 'article', params: { id: article._id } }">{{
            article.title
          }}</router-link>
        </h2>

        <span class="date"> {{ article.date | moment("from", "now") }} </span>
        <router-link :to="{ name: 'article', params: { id: article._id } }">Leer más</router-link>

        <div class="clearfix"></div>
      </article>
    </div>
    <div v-else-if="articles && articles.length < 1">
      No hay artículos para mostrar
    </div>
    <div v-else>Cargando...</div>
  </section>
</template>
<script>
import Global from "../Global";
export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
    };
  },
};
</script>
