// aprendiendo_angular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { ArticleService } from 'src/app/services/article.service';
import { Article } from 'src/app/models/article';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from 'src/app/services/global';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {
  public article!: Article;
  public url: string;

  constructor(private _articleService: ArticleService, private _route: ActivatedRoute, private _router: Router) { 
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe((params) => {
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        response => {
          if(response.article){
            this.article = response.article;
          }else{
            this._router.navigate(['/home']);
          }
        },
        error => {
          console.log(error);
          this._router.navigate(['/home']);
        }
      )
    });
  }

  delete(id:string) {
    Swal.fire({
      title: '¿Estás seguro?',
      text: 'El artículo se eliminará permanentemente',
      icon: 'warning',
      showCancelButton: true,
      showConfirmButton: true,
      confirmButtonColor: '#d33',
      cancelButtonColor: '#3085d6',
      confirmButtonText: 'Borrar',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {
        this._articleService.delete(id).subscribe(
          response => {
            this._router.navigate(['/blog']);
          },
          error => {
            console.log(error);
            this._router.navigate(['/blog']);
          }
        );
        Swal.fire('Artículo borrado', 'El artículo ha sido borrado', 'success');
      } else {
        Swal.fire('Operación cancelada', 'El artículo no ha sido borrado');
      }
    });
  }
}

      

<div class="center">
    <section id="content">
        <article class="article-item article-detail" *ngIf="article">
            <div class="image-wrap" *ngIf="article.image">
                <img src="{{url+ 'get-image/' + article.image}}" alt="{{article.title}}" />
            </div>
            <div class="image-wrap" *ngIf="!article.image">
                <img src="../../../assets/images/default.jpg" alt="{{article.title}}" />
            </div>
            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">
                {{article.date | amLocale: 'es' | amTimeAgo }}
            </span>
            <p>
                {{article.content}}
            </p>
            <div class="buttons">
                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>
            </div>
            <div class="clearfix"></div>
        </article>
    </section>
    <app-sidebar>
    </app-sidebar>
</div>

// aprendiendo_vue/src/components/Article.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" v-if="article">
          <div class="image-wrap">
            <img
              :src="url + 'get-image/' + article.image"
              :alt="article.title"
              v-if="article.image"
            />
            <img
              src="../assets/images/default.jpg"
              :alt="article.title"
              v-else
            />
          </div>

          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date"> {{ article.date | moment("from", "now") }} </span>
          <p>{{ article.content }}</p>

          <div class="clearfix"></div>

          <router-link :to="'/editar/' + article._id" class="btn btn-warning"
            >Editar</router-link
          >
          <a @click="deleteArticle(article._id)" class="btn btn-danger"
            >Eliminar</a
          >
        </article>
      </section>
      <Sidebar></Sidebar>
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Global from "../Global";
import axios from "axios";
import swal from "sweetalert";
export default {
  name: "Article",
  components: {
    Sidebar,
  },
  data() {
    return {
      url: Global.url,
      article: null,
    };
  },
  mounted() {
    var articleId = this.$route.params.id;
    this.getArticle(articleId);
  },
  methods: {
    getArticle(articleId) {
      axios.get(this.url + "article/" + articleId).then((res) => {
        if (res.data.status === "success") {
          this.article = res.data.article;
        }
      });
    },
    deleteArticle(articleId) {
      swal({
        title: "¿Estás seguro?",
        text: "Borrarás permanentemente tu artículo",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          axios.delete(this.url + "article/" + articleId).then((res) => {
            if (res.data.status === "success") {
              swal(
                "Artículo borrado",
                "El artículo se ha borrado correctamente",
                "success"
              );

              this.$router.push("/blog");
            }
          });
        } else {
          swal(
            "Tranquilo no se ha borrado nada",
            "El artículo no se ha borrado",
            "success"
          );
        }
      });
    },
  },
};
</script>
