// aprendiendo_react/src/components/Pelicula.js
import React, { Component } from "react";
import { Link } from "react-router-dom";


class Pelicula extends Component {
    marcar = () => {
        this.props.marcarFavorita(this.props.pelicula, this.props.indice);
    }
    render() {
        const { titulo, image } = this.props.pelicula;
        return (
            <article className="article-item" id="article-template">
                <div className="image-wrap">
                    <img src={image} alt={titulo} />
                </div>

                <h2>{titulo}</h2>
                <span className="date">
                    Hace 5 minutos
                </span>
                <Link to="/blog">Leer más</Link>
                <button onClick={this.marcar}>
                    Marcar como favorita
                </button>

                <div className="clearfix"></div>
            </article>
        );
    }
}

export default Pelicula;

// aprendiendo_vue/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img
        :src="pelicula.image"
        :alt="pelicula.title"
        :title="pelicula.title"
      />
    </div>

    <h2>{{ pelicula.title }}</h2>
    <span
      class="date"
      v-bind:class="{
        yeargreen: pelicula.year >= 2016,
        yearred: pelicula.year < 2016,
      }"
    >
      {{ pelicula.year }}
    </span>
    <a href="#">Leer más</a>
    <input type="button" value="Marcar como favorita" @click="pasarFavoritaAlPadre(pelicula)" />

    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods: {
    pasarFavoritaAlPadre(pelicula){
      this.$emit('favorita', pelicula);
    }
  }
};
</script>
