// aprendiendo_react/src/components/Sidebar.js
import React, { Component } from "react";
import { Link ,Redirect} from "react-router-dom";

class Sidebar extends Component {
    searchRef = React.createRef();
    state = {
        search: '',
        redirect: false
    };
    redirectToSearch = (e) => {
        e.preventDefault();
        this.setState({
            search: this.searchRef.current.value,
            redirect: true
        });
    }
    render() {
        if(this.state.redirect){
            return(
                <Redirect to={'/redirect/' + this.state.search}></Redirect>
            );

        }
        return (
            <aside id="sidebar">
                {
                    this.props.blog === "true" &&
                    <div id="nav-blog" className="sidebar-item">
                        <h3>Puedes hacer esto</h3>
                        <Link to={'/blog/crear'} className="btn btn-success">Crear artículo</Link>
                    </div>
                }


                <div id="search" className="sidebar-item">
                    <h3>Buscador</h3>
                    <p>Encuentra el artículo que buscas</p>
                    <form onSubmit={this.redirectToSearch}>
                        <input type="text" name="search" ref={this.searchRef}/>
                        <input type="submit" name="submit" value="Buscar" className="btn" />
                    </form>
                </div>
            </aside>
        );
    }
}

export default Sidebar;

// aprendiendo_vue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <router-link to="/crear-articulo" class="btn btn-success">Crear artículo</router-link>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el artículo que buscas</p>
      <form @submit.prevent="goSearch">
        <input type="text" name="search" v-model="searchString" />
        <input type="submit" name="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar",
  data() {
    return {
      searchString: null,
    };
  },
  methods: {
    goSearch() {
      this.$router.push("/redirect/" + this.searchString);
    },
  },
};
</script>
