// aprendiendo_react/src/components/Slider.js
import React, { Component } from "react";
import { Link } from "react-router-dom";

class Slider extends Component {
    render() {
        return (
            <div id="slider" className={this.props.size}>
                <h1>{this.props.title}</h1>
                {
                    this.props.btn && 
                    <Link to="/blog" className="btn-white">{this.props.btn}</Link>
                }
            </div>
        );
    }
}

export default Slider;

// aprendiendo_vue/src/components/Slider.vue
<template>
  <div
    id="slider"
    :class="{
      'slider-big': home,
      'slider-small': !home,
    }"
  >
    <h1>{{ texto }}</h1>
    <router-link to="/blog" class="btn-white" v-if="home"
      >Ir al blog</router-link
    >
  </div>
</template>

<script>
export default {
  name: "Slider",
  props: ["texto", "home"],
};
</script>
