// aprendiendo_vue/src/components/Articles.vue
<template>
  <section id="articles-component">
    <div id="articles-list" v-if="articles && articles.length >= 1">
      <article
        class="article-item"
        v-for="article in articles"
        :key="article._id"
      >
        <div class="image-wrap">
          <img
            :src="url + 'get-image/' + article.image"
            :alt="article.title"
            v-if="article.image"
          />
          <img
            src="../assets/images/default.jpg"
            :alt="article.title"
            v-if="!article.image"
          />
        </div>

        <h2>
          <router-link :to="{ name: 'article', params: { id: article._id } }">{{
            article.title
          }}</router-link>
        </h2>

        <span class="date"> {{ article.date | moment("from", "now") }} </span>
        <router-link :to="{ name: 'article', params: { id: article._id } }">Leer más</router-link>

        <div class="clearfix"></div>
      </article>
    </div>
    <div v-else-if="articles && articles.length < 1">
      No hay artículos para mostrar
    </div>
    <div v-else>Cargando...</div>
  </section>
</template>
<script>
import Global from "../Global";
export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
    };
  },
};
</script>

// aprendiendo_react/src/components/Articles.js
import React, { Component } from "react";
import axios from 'axios';
import { Link } from 'react-router-dom';
import Moment from 'react-moment';
import 'moment/locale/es';
import Global from "../Global";
import imageDefault from "../assets/images/default.jpg";

class Articles extends Component {
    url = Global.url;
    state = {
        articles: [],
        status: null
    }
    componentDidMount() {
        var home = this.props.home;
        var search = this.props.search;
        if(home === 'true'){
            this.getLastArticles();

        }else{
            if(search && search !== null && search !== undefined){
                this.getArticlesBySearch(search);
            }else{
                this.getArticles();
            }
            
        }
    }

    getArticlesBySearch = (searched) => {
        axios.get(this.url + 'search/' + searched).then(
            res => {
                if(res.data.articles){
                    this.setState({
                        articles: res.data.articles,
                        status: 'success'
                    });    
                }    
            }
        ).catch(err => {
            this.setState({
                articles: [],
                status: 'success'
            });  
        });
    }

    getLastArticles = () => {
        axios.get(this.url + 'articles/last').then(
            res => {
                this.setState({
                    articles: res.data.articles,
                    status: 'success'
                })       
            }
        )
    }

    getArticles = () => {
        axios.get(this.url + 'articles').then(
            res => {
                this.setState({
                    articles: res.data.articles,
                    status: 'success'
                })       
            }
        )
    }
    render() {
        if (this.state.articles.length >= 1) {
            var listArticles = this.state.articles.map((article) => {
                return (
                    <article className="article-item" key={article._id} id="article-template">
                        <div className="image-wrap">

                            {
                                article.image !== null ?
                                (<img src={this.url + 'get-image/' + article.image} alt={article.title} />)
                                : ( <img src={imageDefault} alt={article.title} />)
                            }

                           
                        </div>

                        <h2>{article.title}</h2>
                        <span className="date">
                            <Moment locale="es" fromNow>{article.date}</Moment>
                        </span>
                        <Link to={"/blog/articulo/" + article._id}>Leer más</Link>

                        <div className="clearfix"></div>
                    </article>
                )
            });
            return (
                <div id="articles">
                    {listArticles}
                </div>
            );
        } else {
            if (this.state.articles.length === 0 && this.state.status === 'success') {
                return (
                    <div id="articles">
                        <h2 className="subheader">No hay artículos para mostrar</h2>
                        <p>Todavía no hay contenido en esta sección</p>
                    </div>
                );
            } else {
                return (
                    <div id="articles">
                        <h2 className="subheader">Cargando...</h2>
                        <p>Espere mientras carga el contenido</p>
                    </div>
                );
            }
        }

    }
}

export default Articles;
