// aprendiendo_vue/src/components/Article.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" v-if="article">
          <div class="image-wrap">
            <img
              :src="url + 'get-image/' + article.image"
              :alt="article.title"
              v-if="article.image"
            />
            <img
              src="../assets/images/default.jpg"
              :alt="article.title"
              v-else
            />
          </div>

          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date"> {{ article.date | moment("from", "now") }} </span>
          <p>{{ article.content }}</p>

          <div class="clearfix"></div>

          <router-link :to="'/editar/' + article._id" class="btn btn-warning"
            >Editar</router-link
          >
          <a @click="deleteArticle(article._id)" class="btn btn-danger"
            >Eliminar</a
          >
        </article>
      </section>
      <Sidebar></Sidebar>
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Global from "../Global";
import axios from "axios";
import swal from "sweetalert";
export default {
  name: "Article",
  components: {
    Sidebar,
  },
  data() {
    return {
      url: Global.url,
      article: null,
    };
  },
  mounted() {
    var articleId = this.$route.params.id;
    this.getArticle(articleId);
  },
  methods: {
    getArticle(articleId) {
      axios.get(this.url + "article/" + articleId).then((res) => {
        if (res.data.status === "success") {
          this.article = res.data.article;
        }
      });
    },
    deleteArticle(articleId) {
      swal({
        title: "¿Estás seguro?",
        text: "Borrarás permanentemente tu artículo",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          axios.delete(this.url + "article/" + articleId).then((res) => {
            if (res.data.status === "success") {
              swal(
                "Artículo borrado",
                "El artículo se ha borrado correctamente",
                "success"
              );

              this.$router.push("/blog");
            }
          });
        } else {
          swal(
            "Tranquilo no se ha borrado nada",
            "El artículo no se ha borrado",
            "success"
          );
        }
      });
    },
  },
};
</script>

// aprendiendo_react/src/components/Article.js
import React, { Component } from "react";
import { Link, Redirect } from "react-router-dom";
import axios from "axios";
import swal from "sweetalert";
import Global from "../Global";
import Sidebar from "./Sidebar";
import Moment from "react-moment";
import 'moment/locale/es';
import imageDefault from "../assets/images/default.jpg";

class Article extends Component {
    url = Global.url;
    state = {
        article: false,
        status: null
    };
    componentDidMount() {
        this.getArticle();
    }
    getArticle = () => {
        var id = this.props.match.params.id;
        axios.get(this.url + 'article/' + id).then(
            res => {
                this.setState({
                    article: res.data.article,
                    status: 'success'
                });
            }
        ).catch(err => {
            this.setState({
                article: false,
                status: 'success'
            });
        });
    }

    deleteArticle = (id) => {
        swal({
            title: '¿Estás seguro?',
            text: "Borrarás permanentemente tu artículo",
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                axios.delete(this.url + 'article/' + id).then(
                    res => {
                        this.setState({
                            article: res.data.article,
                            status: 'deleted'
                        });
                        swal(
                            'Artículo borrado',
                            'El artículo ha sido borrado correctamente',
                            'success'
                        );
                    }
                )
            } else {
                swal(
                    'Tranquilo no se ha borrado nada',
                    'El artículo no se ha borrado',
                    'success'
                );
            }
        })
    }

    render() {
        if (this.state.status === 'deleted') {
            return <Redirect to="/blog"></Redirect>
        }
        var article = this.state.article;
        return (
            <div className="center">
                <section id="content">
                    {
                        this.state.article &&
                        <article className="article-item article-detail">
                            <div className="image-wrap">

                                {
                                    article.image !== null ?
                                        (<img src={this.url + 'get-image/' + article.image} alt={article.title} />)
                                        : (<img src={imageDefault} alt={article.title} />)
                                }


                            </div>

                            <h1 className="subheader">{article.title}</h1>
                            <span className="date">
                                <Moment locale="es" fromNow>{article.date}</Moment>
                            </span>
                            <p>{article.content}</p>
                            <button onClick={
                                () => {
                                    this.deleteArticle(article._id)
                                }


                            } className="btn btn-danger">Eliminar</button>
                            <Link to={"/blog/editar/"+article._id} className="btn btn-warning">Editar</Link>
                            <div className="clearfix"></div>
                        </article>
                    }
                    {
                        !this.state.article && this.state.status === 'success' &&
                        <div id="article">
                            <h2 className="subheader">El artículo no exite</h2>
                            <p>Inténtalo de nuevo más tarde</p>
                        </div>
                    }
                    {
                        this.state.status == null &&
                        <div id="article">
                            <h2 className="subheader">Cargando...</h2>
                            <p>Espere unos segundos</p>
                        </div>
                    }
                </section>
                <Sidebar></Sidebar>
            </div>
        );
    }
}

export default Article;
