// aprendiendo_angular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {
  public title: string;
  public user: any;
  public campo!: string;

  constructor() { 
    this.title = "Formulario";
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    }
  }

  ngOnInit(): void {
  }

  onSubmit() {
    alert("Formulario enviado!!");
    console.log(this.user);
  }

  hasDadoClick() {
    alert("Has dado click");
  }

  hasSalido(){
    alert("Has salido");
  }

  hasPulsado() {
    alert("Has pulsado una tecla");
  }

}

<app-slider [nombre]="'Formulario'" [size]="'small'">
</app-slider>
<div class="center">
    <section id="content">
        <h2 class="subheader">{{title}}</h2>
       <!-- <div id="datos-al-vuelo" *ngIf="user.nombre">
            <h3 class="subheader">Datos al vuelo</h3>
            <ul>
                <li>{{user.nombre}}</li>
                <li>{{user.apellidos}}</li>
                <li>{{user.bio}}</li>
                <li>{{user.genero}}</li>
            </ul>
        </div>
        -->
        <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)] = "user.nombre" required pattern="[a-zA-Z]+"/>
                <small *ngIf="!nombre.valid && nombre.touched">
                    El nombre no es válido
                </small>
            </div>

            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)] = "user.apellidos" required/>
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Los apellidos no son válidos
                </small>
            
            </div>

            <div class="form-group">
                <label for="bio">Biografia</label>
                <textarea name="bio" #bio="ngModel" [(ngModel)] = "user.bio" required></textarea>
                <small *ngIf="!bio.valid && bio.touched">
                    La biografía no es válida
                </small>
            </div>

            <div class="form-group radibuttons">
                <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)] = "user.genero" required/> Hombre
                <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)] = "user.genero"/> Mujer
                <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)] = "user.genero"/> Otro
                <small *ngIf="!genero.valid && genero.touched">
                    El género no es válido
                </small>
            
            </div>

            <div class="clearfix"></div>

            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid"/>

        </form>
        <h2 class="subheader">Eventos</h2>
        <button (click)="hasDadoClick()">Dale click</button>
        <input type="text" [(ngModel)]="campo" (keyup)="hasPulsado()" />
        {{campo}}
    </section>
    <app-sidebar>
    </app-sidebar>
</div>

// aprendiendo_react/src/components/Formulario.js
import React, { Component } from "react";
import Slider from './Slider';
import Sidebar from './Sidebar';

class Formulario extends Component {
    nombreRef = React.createRef();
    apellidosRef = React.createRef();
    bioRef = React.createRef();
    generoHombreRef = React.createRef();
    generoMujerRef = React.createRef();
    generoOtroRef = React.createRef();
    state = {
        user: {}
    };
    recibirFormulario = (e) => {
        e.preventDefault();
        var genero = "hombre";
        if (this.generoHombreRef.current.checked) {
            genero = this.generoHombreRef.current.value;
        } else {
            if (this.generoMujerRef.current.checked) {
                genero = this.generoMujerRef.current.value;
            } else {
                genero = this.generoOtroRef.current.value;
            }
        }
        var user = {
            nombre: this.nombreRef.current.value,
            apellidos: this.apellidosRef.current.value,
            bio: this.bioRef.current.value,
            genero: genero
        }

        this.setState({
            user: user
        })

        console.log("Formulario enviado");
        console.log(user);

    }
    render() {
        if (this.state.user.nombre) {
            var user = this.state.user;
        }
        return (
            <div id="formulario">
                <Slider
                    title="Formulario"
                    size="slider-small"
                >
                </Slider>
                <div className="center">
                    <div id="content">
                        <h2 className="subheader">Formulario de usuario</h2>
                        {/** Mostrar datos del formulario */}
                        {
                            this.state.user.nombre &&
                            <div id="user-data">
                                <p>Nombre: <strong>{user.nombre}</strong></p>
                                <p>Apellidos: <strong>{user.apellidos}</strong></p>
                                <p>Biografía: <strong>{user.bio}</strong></p>
                                <p>Genero: <strong>{user.genero}</strong></p>
                            </div>
                        }


                        {/** Crear un formulario */}
                        <form className="mid-form" onSubmit={this.recibirFormulario} onChange={this.recibirFormulario}>
                            <div className="form-group">
                                <label htmlFor="nombre">Nombre</label>
                                <input type="text" name="nombre" ref={this.nombreRef} />
                            </div>

                            <div className="form-group">
                                <label htmlFor="apellidos">Apellidos</label>
                                <input type="text" name="apellidos" ref={this.apellidosRef} />
                            </div>

                            <div className="form-group">
                                <label htmlFor="bio">Biografia</label>
                                <textarea name="bio" ref={this.bioRef}></textarea>
                            </div>

                            <div className="form-group radibuttons">
                                <input type="radio" name="genero" value="hombre" ref={this.generoHombreRef} /> Hombre
                                <input type="radio" name="genero" value="mujer" ref={this.generoMujerRef} /> Mujer
                                <input type="radio" name="genero" value="otro" ref={this.generoOtroRef} /> Otro
                            </div>

                            <div className="clearfix"></div>

                            <input type="submit" value="Enviar" className="btn btn-success" />

                        </form>
                    </div>
                    <Sidebar></Sidebar>
                </div>

            </div>
        );
    }
}

export default Formulario;
