// aprendiendo_react/src/components/Home.js
import React, { Component } from "react";
import Slider from './Slider';
import Sidebar from './Sidebar';
import Articles from "./Articles";

class Home extends Component {
    render() {
        return (
            <div id="home">
                <Slider
                    title="Bienvenido al Curso de React con Víctor Robles de victorroblesweb.es"
                    btn="Ir al blog"
                    size="slider-big"
                >
                </Slider>
                <div className="center">

                    <div id="content">
                        <h2 className="subheader">Últimos artículos</h2>
                        <Articles home="true"></Articles>
                    </div>
                    <Sidebar></Sidebar>
                </div>

            </div>
        );
    }
}

export default Home;

// aprendiendo_angular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  providers: [ArticleService]
})
export class HomeComponent implements OnInit {
  public title: string;
  public articles!: Article[];

  constructor(private _articleService: ArticleService) {
    this.title = "Últimos artículos";
   }

  ngOnInit(): void {
    this._articleService.getArticles(true).subscribe(
      response => {
        if (response.articles) {
          this.articles = response.articles;
          console.log(this.articles);
        } else {

        }
      },
      error => {
        console.log(error);
      }
    );
  }

}

<app-slider [nombre]="'Bienvenido al Curso de Angular con Víctor Robles de victorroblesweb.es'">
</app-slider>
<div class="center">
    <section id="content">
        <h2 class="subheader">{{title}}</h2>
        <app-articles [articles]="articles"></app-articles>
    </section>
    <app-sidebar>
    </app-sidebar>
</div>
